FROM alpine

RUN apk update && apk add curl

COPY test.sh /app/test.sh

WORKDIR /app

# fix Unix-style line endings (if built using windows client)
RUN sed -i -e 's/\r$//' test.sh

ENTRYPOINT ["sh"]
CMD ["test.sh"]
